name: CI

on:
  pull_request:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

env:
  UV_FROZEN: "1"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install
        run: make sync

      - name: Lint
        run: make lint

      - name: Type check
        run: make pyright

      - name: Test
        run: make test
