import { useEffect, useRef, useState } from "react";
import { ChevronDown, ChevronUp, ImagePlus, Plus, Save, Trash2, X } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import "./lab-editor.css";

type Field = Record<string, unknown> & { id: string; type: string; label: string };
type Block = { type: "markdown"; content: string } | { type: "field"; field: Field };

const quote = (value: unknown) => `"${String(value).replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
function directive(field: Field) {
  const attrs = Object.entries(field).filter(([key, value]) => key !== "type" && key !== "section" && value !== undefined && value !== null).map(([key, value]) => {
    if (key === "options" && Array.isArray(value)) return `${key}=${quote(value.map((item: any) => `${item.id}:${item.label}`).join("|"))}`;
    if ((key === "rows" || key === "columns") && Array.isArray(value)) return `${key}=${quote(value.map((item: any) => key === "rows" ? `${item.id}:${item.label}` : `${item.id}:${item.label}:${item.input_type ?? "text"}${item.unit ? `:${item.unit}` : item.options ? `:${item.options.join(";")}` : ""}`).join("|"))}`;
    if (Array.isArray(value)) return `${key}=${quote(value.join(","))}`;
    return `${key}=${typeof value === "boolean" || typeof value === "number" ? value : quote(value)}`;
  });
  return `{{ ${field.type} ${attrs.join(" ")} }}`;
}

export default function LabVisualEditor({ slug, token, onClose, onPublished }: { slug: string; token: string; onClose: () => void; onPublished: (message: string) => void }) {
  const [blocks, setBlocks] = useState<Block[]>([]), [busy, setBusy] = useState(true), [error, setError] = useState("");
  const imageInput = useRef<HTMLInputElement>(null), activeMarkdown = useRef(0);
  useEffect(() => { fetch(`/api/labs/admin/${slug}/editor`, { headers: { Authorization: `Bearer ${token}` } }).then(async r => { if (!r.ok) throw new Error((await r.json()).detail); return r.json(); }).then(result => setBlocks(result.definition.blocks)).catch(reason => setError(String(reason))).finally(() => setBusy(false)); }, [slug, token]);
  const change = (index: number, block: Block) => setBlocks(current => current.map((item, i) => i === index ? block : item));
  const move = (index: number, delta: number) => setBlocks(current => { const copy = [...current], target = index + delta; if (target < 0 || target >= copy.length) return current; [copy[index], copy[target]] = [copy[target], copy[index]]; return copy; });
  const addField = () => setBlocks(current => [...current, { type: "field", field: { id: `champ_${Date.now()}`, type: "textarea", label: "Nouvelle réponse", rows: 3 } }]);
  const uploadImage = async (file?: File) => { if (!file) return; const form = new FormData(); form.append("file", file); const response = await fetch(`/api/labs/admin/${slug}/assets`, { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: form }); if (!response.ok) { setError((await response.json()).detail); return; } const result = await response.json(); const index = activeMarkdown.current; const block = blocks[index]; if (block?.type === "markdown") change(index, { ...block, content: `${block.content}\n\n![${result.name}](${result.url})` }); };
  const publish = async () => { setBusy(true); setError(""); const source = blocks.map(block => block.type === "markdown" ? block.content.trim() : directive(block.field)).join("\n\n"); const response = await fetch(`/api/labs/admin/${slug}/editor`, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ source }) }); if (!response.ok) { setError((await response.json()).detail ?? "Publication impossible"); setBusy(false); return; } const result = await response.json(); onPublished(`Version ${result.version} publiée depuis l’éditeur visuel.`); onClose(); };
  return <div className="lab-visual-backdrop"><section className="lab-visual-editor"><header><div><span className="lab-kicker">Éditeur visuel</span><h2>Modifier {slug}</h2></div><button onClick={onClose} aria-label="Fermer"><X /></button></header>{error && <div className="lab-inline-error">{error}</div>}<div className="lab-visual-toolbar"><button className="lab-button" onClick={() => setBlocks(current => [...current, { type: "markdown", content: "## Nouvelle section\n\nVotre texte." }])}><Plus size={17} /> Ajouter du texte</button><button className="lab-button" onClick={addField}><Plus size={17} /> Ajouter un champ interactif</button><button className="lab-button lab-button--primary" disabled={busy} onClick={publish}><Save size={17} /> Publier la version</button></div><div className="lab-visual-canvas">{busy && !blocks.length ? <p>Chargement…</p> : blocks.map((block, index) => <article className="lab-editor-block" key={index}><div className="lab-editor-block__actions"><button onClick={() => move(index, -1)}><ChevronUp size={15} /></button><button onClick={() => move(index, 1)}><ChevronDown size={15} /></button><button onClick={() => setBlocks(current => current.filter((_, i) => i !== index))}><Trash2 size={15} /></button></div>{block.type === "markdown" ? <><div className="lab-editor-preview"><ReactMarkdown remarkPlugins={[remarkGfm]}>{block.content}</ReactMarkdown></div><details><summary>Modifier ce contenu</summary><textarea rows={8} value={block.content} onChange={event => change(index, { ...block, content: event.target.value })} /><button className="lab-button" onClick={() => { activeMarkdown.current = index; imageInput.current?.click(); }}><ImagePlus size={16} /> Insérer une image</button></details></> : <FieldEditor field={block.field} onChange={field => change(index, { type: "field", field })} />}</article>)}</div><input ref={imageInput} hidden type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={event => { void uploadImage(event.target.files?.[0]); event.currentTarget.value = ""; }} /></section></div>;
}

function FieldEditor({ field, onChange }: { field: Field; onChange: (field: Field) => void }) {
  const set = (key: string, value: unknown) => onChange({ ...field, [key]: value });
  return <div className="lab-field-editor"><strong>Champ interactif</strong><div className="lab-field-editor__grid"><label>Type<select value={field.type} onChange={e => set("type", e.target.value)}>{["text", "textarea", "number", "checkbox", "select", "radio", "image", "teacher_validation", "table", "matrix"].map(type => <option key={type}>{type}</option>)}</select></label><label>Identifiant<input value={field.id} onChange={e => set("id", e.target.value)} /></label><label>Libellé<input value={field.label} onChange={e => set("label", e.target.value)} /></label><label className="lab-field-required"><input type="checkbox" checked={Boolean(field.required)} onChange={e => set("required", e.target.checked)} /> Obligatoire</label></div>{(field.type === "select" || field.type === "radio") && <label>Choix (un par ligne, identifiant:libellé)<textarea rows={4} value={Array.isArray(field.options) ? (field.options as any[]).map(item => `${item.id}:${item.label}`).join("\n") : ""} onChange={e => set("options", e.target.value.split("\n").filter(Boolean).map(line => { const [id, ...label] = line.split(":"); return { id, label: label.join(":") || id }; }))} /></label>} {(field.type === "table" || field.type === "matrix") && <p className="lab-editor-note">Les lignes et colonnes existantes sont conservées. Leur éditeur détaillé sera ajouté dans une prochaine itération.</p>}</div>;
}
