"""API publique du noyau ChatKit (schémas, outils et workflow)."""

from .outputs import (
    JsonSchemaOutputBuilder,
    build_output_type_from_response_format,
    create_response_format_from_pydantic,
    format_step_output,
    lookup_known_output_type,
    sanitize_model_name,
    structured_output_as_json,
)
from .schemas import *  # noqa: F401,F403 - réexportation contrôlée
from .tools import (
    FunctionTool,
    ImageGeneration,
    ImageGenerationTool,
    ModelSettings,
    WebSearchTool,
    build_file_search_tool,
    build_image_generation_tool,
    build_model_settings,
    build_weather_function_tool,
    build_web_search_tool,
    build_widget_validation_function_tool,
    clone_tools,
    coerce_agent_tools,
    coerce_model_settings,
    extract_vector_store_ids,
    normalize_image_generation_field,
    sanitize_web_search_user_location,
    validate_widget_definition,
    web_search_preview,
    WidgetValidationResult,
)
from .workflow_runner import (
    WorkflowEndState,
    WorkflowExecutionError,
    WorkflowInput,
    WorkflowRunSummary,
    WorkflowStepStreamUpdate,
    WorkflowStepSummary,
    run_workflow,
)

__all__ = [
    "FunctionTool",
    "ImageGeneration",
    "ImageGenerationTool",
    "JsonSchemaOutputBuilder",
    "ModelSettings",
    "WebSearchTool",
    "WorkflowEndState",
    "WorkflowExecutionError",
    "WorkflowInput",
    "WorkflowRunSummary",
    "WorkflowStepStreamUpdate",
    "WorkflowStepSummary",
    "build_file_search_tool",
    "build_image_generation_tool",
    "build_model_settings",
    "build_output_type_from_response_format",
    "build_weather_function_tool",
    "build_web_search_tool",
    "build_widget_validation_function_tool",
    "clone_tools",
    "coerce_agent_tools",
    "coerce_model_settings",
    "create_response_format_from_pydantic",
    "extract_vector_store_ids",
    "format_step_output",
    "lookup_known_output_type",
    "normalize_image_generation_field",
    "run_workflow",
    "sanitize_model_name",
    "sanitize_web_search_user_location",
    "structured_output_as_json",
    "validate_widget_definition",
    "web_search_preview",
    "WidgetValidationResult",
]
__all__.extend(name for name in globals() if name.endswith("Schema"))
